In [1]:
import numpy as np

In [2]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
print(M.shape)

(3, 3)


In [4]:
print(type(M))

<class 'numpy.ndarray'>


In [5]:
print("array shape", M.shape)
print("array type", type(M))

array shape (3, 3)
array type <class 'numpy.ndarray'>


In [6]:
print(M)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**Below is a column vector or a column matrix.**

In [7]:
v = np.array([[1],[2],[3]])
print(v)

[[1]
 [2]
 [3]]


In [8]:
print(v.shape)

(3, 1)


**one-dimensional numpy array**

In [9]:
u = np.array([1,2,3])
print(u)
print(u.shape)

[1 2 3]
(3,)


**Row vector**

In [10]:
q = np.array([[1, 2, 3]])
print(q)
print(q.shape)

[[1 2 3]]
(1, 3)


**Print one dimentional array, column vector and row vector**

In [11]:
print(u.shape, v.shape, q.shape)

(3,) (3, 1) (1, 3)


In [19]:
v1 = np.array([1,2,3])
print(v1)
print(v1.shape)

[1 2 3]
(3,)


In [21]:
v2 = np.array([4,5,6])
print(v2)
print(v2.shape)

[4 5 6]
(3,)


In [22]:
v3 = np.array([7,8,9])
print(v3)
print(v3.shape)

[7 8 9]
(3,)


In [23]:
M = np.vstack([v1,v2,v3])


In [25]:
print(M)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print("shape of M", M.shape)
print("type of M", type(M))

shape of M (3, 3)
type of M <class 'numpy.ndarray'>


In [26]:
N = np.hstack([v1,v2,v3])

In [27]:
print(N)

[1 2 3 4 5 6 7 8 9]


In [28]:
print("shape of N", N.shape)
print("type of N", type(N))

shape of N (9,)
type of N <class 'numpy.ndarray'>


In [29]:
O = np.hstack([[v1],[v2],[v3]])

In [30]:
print("shape of O", O.shape)
print("type of O", type(O))

shape of O (1, 9)
type of O <class 'numpy.ndarray'>


In [31]:
print(O)

[[1 2 3 4 5 6 7 8 9]]


**Matrix indexing**

In [ ]:
print(M[1,2])

6


In Python indexing,** rows and columns are zero-based**, **meaning the first row is indexed as 0, the second row as 1, and so on. Similarly, the first column is indexed as 0, the second column as 1, and so on.**

So, when you write M[1, 2], you are accessing the element at the second row (index 1) and the third column (index 2), which corresponds to the value 6.

To summarize, M[1, 2] is a valid way to access the element in the second row and the third column of the matrix M, which is indeed 6.

In [ ]:
print(M)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
print(M[0,0])

1


In [ ]:
print(M[:2,1:3])

[[2 3]
 [5 6]]


 It has three steps
- `M[:2, 1:3]` is a slicing operation.
- `[:2]` specifies the rows to include in the submatrix, which means rows from the beginning (index 0) up to, but not including, index 2 (i.e., rows 0 and 1).
- `[1:3]` specifies the columns to include in the submatrix, which means columns from index 1 (inclusive) up to, but not including, index 3 (i.e., columns 1 and 2).

So, the expression `M[:2, 1:3]` extracts a submatrix from matrix `M` consisting of rows 0 and 1 (the first two rows) and columns 1 and 2 (the second and third columns). This submatrix is a 2x2 matrix formed from the top-left portion of the original 3x3 matrix `M`.


**Warning**

**Question (stackoverflow):**
When I multiply two numpy arrays of sizes (n x n)*(n x 1), I get a matrix of size (n x n). Following normal matrix multiplication rules, a (n x 1) vector is expected, but I simply cannot find any information about how this is done in Python's Numpy module.

In [33]:
M = np.array([[1,2,3],[4,5,6]])
print(M)
print(M.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [34]:
v = np.array([1,2,3])
print(v)
print(v.shape)

[1 2 3]
(3,)


In [35]:
print(M)
print("shape of M", M.shape)
print("type of M", type(M))

[[1 2 3]
 [4 5 6]]
shape of M (2, 3)
type of M <class 'numpy.ndarray'>


In [ ]:
print(v)
print("shape of v", v.shape)
print("type of v", type(v))

[1 2 3]
shape of v (3,)
type of v <class 'numpy.ndarray'>


In [ ]:
print(M*v)

[[ 1  4  9]
 [ 4 10 18]]


In [ ]:
n = M*v

In [ ]:
print(n)
print("shape of n", n.shape)
print("type of n", type(n))

[[ 1  4  9]
 [ 4 10 18]]
shape of n (2, 3)
type of n <class 'numpy.ndarray'>



 **Solution**

 In NumPy, when you multiply a (n x n) matrix by a (n x 1) column vector using the np.dot() function or the @ operator (matrix multiplication operator), the result will indeed be a (n x 1) column vector, which is the expected behavior based on matrix multiplication rule

In [12]:
p = M@v

In [13]:
print(p)
print("shape of p", p.shape)
print("type of p", type(p))

[[14]
 [32]
 [50]]
shape of p (3, 1)
type of p <class 'numpy.ndarray'>


In [14]:
q = np.dot(M,v)

In [15]:
print(q)
print("shape of q", q.shape)
print("type of q", type(q))

[[14]
 [32]
 [50]]
shape of q (3, 1)
type of q <class 'numpy.ndarray'>
